name: .NET Build & Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true

      - name: Restore
        run: dotnet restore --nologo

      - name: Build
        run: dotnet build --configuration Release --no-restore --nologo

      - name: Test (with coverage)
        run: |
          dotnet test \
            --no-build \
            --verbosity normal \
            --logger trx \
            --results-directory TestResults \
            --collect:"XPlat Code Coverage"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          path: |
            TestResults/**/*.trx
            TestResults/**/coverage.cobertura.xml

      - name: Generate coverage summary
        if: always()
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: TestResults/**/coverage.cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          output: both
          hide_complexity: true

      - name: Add coverage to job summary
        if: always()
        run: |
          if [ -f code-coverage-results.md ]; then
            cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
          fi
