name: Pack (Tag)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to (re)pack and draft release (e.g. v0.2.0)'
        required: true
        type: string

jobs:
  pack:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout (tag push)
        if: github.event_name != 'workflow_dispatch'
        uses: actions/checkout@v4

      - name: Checkout (manual dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore --nologo

      - name: Build
        run: dotnet build --configuration Release --no-restore --nologo

      - name: Pack
        run: dotnet pack Xbrl.InstanceBuilder.fsproj --configuration Release --no-build --output artifacts

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: artifacts/*.nupkg

      - name: Create GitHub Release (draft, tag push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: artifacts/*.nupkg
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            自動作成されたドラフトリリースです。詳細は CHANGELOG を参照してください。
            https://github.com/divergen371/XbrlInstanceBuilder/blob/${{ github.ref_name }}/CHANGELOG.md

      - name: Create GitHub Release (draft, manual dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: artifacts/*.nupkg
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.tag }}
          body: |
            自動作成されたドラフトリリースです。詳細は CHANGELOG を参照してください。
            https://github.com/divergen371/XbrlInstanceBuilder/blob/${{ inputs.tag }}/CHANGELOG.md
